apiVersion: v2
name: pelican-panel
description: A Helm chart for Kubernetes
type: application
version: 0.4.2

# renovate: image=ghcr.io/pelican-dev/panel
appVersion: "v1.0.0-beta30"

maintainers:
  - name: nikkischnelle
