apiVersion: v2
name: pelican-panel
description: A Helm chart for Kubernetes
type: application
version: 0.4.14

# renovate: depName=ghcr.io/pelican-dev/panel
appVersion: "v1.0.0-beta33"

maintainers:
  - name: nikkischnelle
