pelican:
  # -- the url where the panel will be accessible
  appUrl: "https://example.com"
  # -- pvc settings for pelican data (plugins, fonts, if used: sqlite)
  dataPVC:
    # -- enable or disable automatic pvc creation and mounting
    enabled: true
    # -- storage class for automatic pvc creation
    storageClassName: Null
    # -- access modes for pvc
    accessModes:
      - ReadWriteOnce
    # -- size of pvc
    size: 4Gi
  # -- pvc settings for pelican logs
  logsPVC:
    # -- enable or disable automatic pvc creation and mounting
    enabled: true
    # -- storage class for automatic pvc creation
    storageClassName: Null
    # -- access modes for pvc
    accessModes:
      - ReadWriteOnce
    # -- size of pvc
    size: 1Gi
  # -- external database settings
  externalDatabase:
    # -- enable or disable external database usage
    enabled: false
    # -- host of the external database
    host: ""
    # -- port of the external database
    port: 5432
    # -- name of the database
    database: ""
    # -- auth settings for external database
    auth:
      # -- name of an external secret containing username and password
      externalSecretName: ""
      # -- key in the external secret for the username
      usernameKey: ""
      # -- key in the external secret for the password
      passwordKey: ""
  # -- external redis settings
  redis:
    # -- enable or disable external redis usage
    enabled: false
    # -- host of the external redis
    host: ""
    # -- port of the external redis
    port: 6379
    # -- auth settings for external redis
    auth:
      # -- enable or disable redis password usage
      enabled: false
      # -- name of an external secret containing the password
      externalSecretName: ""
      # -- key in the external secret for the password
      passwordKey: ""

  # -- backup settings used for game servers
  backup:
    # -- automatic provision of s3 backup settings
    s3:
      # -- enable or disable automatic provision of s3 backup settings
      enabled: false
      # -- use path style endpoint (needed for some s3 compatible providers)
      usePathStyleEndpoint: false
      # -- s3 region; overriden if regionKey is set in existingSecret
      region: ""
      # -- s3 bucket name; overriden if bucketKey is set in existingSecret
      bucket: ""
      # -- s3 endpoint url; overriden if endpointKey is set in existingSecret
      endpoint: ""
      # -- REQUIRED! existing secret to get s3 settings from.
      existingSecret:
        # -- name of the existing secret
        name: ""
        # -- optional key in the existing secret for the s3 region
        regionKey: ""
        # -- optional key in the existing secret for the s3 bucket. overrides the bucket name above
        bucketKey: ""
        # -- optional key in the existing secret for the s3 endpoint
        endpointKey: ""
        # -- REQUIRED! key in the existing secret for the s3 access key id
        accessKeyIdKey: ""
        # -- REQUIRED! key in the existing secret for the s3 secret access key
        secretAccessKeyKey: ""

# -- download plugins using an init container
pluginDownloader:
  # -- image used to download and unzip plugins
  image:
    repository: curlimages/curl
    tag: latest
    pullPolicy: Always
  # -- download repositories of multiple plugins
  repoDownloads:
    - url: "https://github.com/pelican-dev/plugins/archive/refs/heads/main.zip"
      replaceExisting: false
      plugins:
        - "minecraft-modrinth"
        - "mclogs-uploader"
        - "robo-avatars"
        - "snowflakes"
  # -- download plugin zips directly
  directDownloads: []
    # - url: "https://example.com/path/to/plugin.zip"
    #   name: "my-plugin"
    #   replaceExisting: false

# -- network policy settings
networkPolicy:
  # -- enable or disable network policy creation
  enabled: true
  # -- default policies
  defaultPolicy:
    # -- traefik ingress
    traefikIngress:
      # -- enable network policy rule to allow ingress from traefik
      enabled: true
      # -- set the namespace selector to select the namespace of your traefik installation
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    # -- coreDNS egress
    coreDNSEgress:
      # -- enable network policy rule to allow egress to coreDNS
      enabled: true
      # -- set the namespace selector to select the namespace of your coreDNS installation
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      # -- set the pod selector to select the coreDNS pods
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    # -- allow all https egress; every egress connection to port 443
    allHttpsEgress:
      # -- enable network policy rule to allow all https egress
      enabled: true

  # -- additional ingress rules for the network policy
  ingressRules: []
    # - from:
    #     - podSelector:
    #         matchLabels:
    #           app: my-app
    #   ports:
    #     - protocol: TCP
    #       port: 80
  # -- additional egress rules for the network policy
  egressRules: []
    # - to:
    #     - podSelector:
    #         matchLabels:
    #           app: my-database
    #   ports:
    #     - protocol: TCP
    #       port: 3306

# -- main application image settings
image:
  repository: ghcr.io/pelican-dev/panel
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 82
  fsGroupChangePolicy: "Always"

securityContext:
  runAsUser: 82
  runAsGroup: 82
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
      # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
    - chart-example.local
  # List of rules and filters applied.
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources:
  limits:
    cpu: 100m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe: &probe
  httpGet:
    path: /up
    port: http

  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe: *probe

# Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
