apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pelican-panel.fullname" . }}
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pelican-panel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pelican-panel.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: {{ include "pelican-panel.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pelican-panel.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.pelican.externalDatabase.enabled }}
        - name: wait-for-db
          image: busybox
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            limits:
              memory: "32Mi"
              cpu: "50m"
            requests:
              memory: "32Mi"
              cpu: "10m"
          command:
          - sh
          - -c
          - |
            until nc -z $DB_HOST $DB_PORT; do
              echo "Waiting for MariaDB..."
              sleep 3
            done
          env:
          - name: DB_HOST
            value: {{ .Values.pelican.externalDatabase.host | quote }}
          - name: DB_PORT
            value: "{{ .Values.pelican.externalDatabase.port }}"
        {{- end }}
        {{- if .Values.pelican.redis.enabled }}
        - name: wait-for-redis
          image: busybox
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            limits:
              memory: "32Mi"
              cpu: "50m"
            requests:
              memory: "32Mi"
              cpu: "10m"
          command:
            - sh
            - -c
            - |
              until nc -z $REDIS_HOST $REDIS_PORT; do
                echo "Waiting for Redis..."
                sleep 3
              done
          env:
            - name: REDIS_HOST
              value: {{ .Values.pelican.redis.host | quote }}
            - name: REDIS_PORT
              value: "{{ .Values.pelican.redis.port }}"
        {{- end }}
        - name: plugin-downloader
          image: "{{ .Values.pluginDownloader.image.repository }}:{{ .Values.pluginDownloader.image.tag }}"
          imagePullPolicy: {{ .Values.pluginDownloader.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          volumeMounts:
            - name: pelican-data
              mountPath: /pelican-data
            - name: plugin-downloader-script
              mountPath: /scripts
            - name: temp
              mountPath: /tmp
          command:
            - sh
            - /scripts/plugin-downloader-script.sh
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: caddy-config
            mountPath: /etc/caddy
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.pelican.logsPVC.enabled }}
          - name: logs
            mountPath: /var/www/html/storage/logs
          - name: temp
            mountPath: /tmp
          {{- end }}
          {{- if .Values.pelican.dataPVC.enabled }}
          - name: pelican-data
            mountPath: /pelican-data
          {{- end }}
          - name: framework-cache
            mountPath: /var/www/html/storage/framework/cache
          - name: filament-cache
            mountPath: /var/www/html/bootstrap/cache
          - name: framework-view-cache
            mountPath: /var/www/html/storage/framework/views/
          - name: framework-sessions
            mountPath: /var/www/html/storage/framework/sessions
          env:
          - name: XDG_DATA_HOME
            value: /pelican-data
          - name: APP_URL
            value: {{ .Values.pelican.appUrl | quote }}
          {{- if .Values.pelican.appName }}
          - name: APP_NAME
            value: {{ .Values.pelican.appName | quote }}
          {{- end }}
          {{- if .Values.pelican.externalDatabase.enabled }}
          - name: DB_HOST
            value: {{ .Values.pelican.externalDatabase.host | quote }}
          - name: DB_PORT
            value: "{{ .Values.pelican.externalDatabase.port }}"
          - name: DB_DATABASE
            value: {{ .Values.pelican.externalDatabase.database | quote }}
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.externalDatabase.auth.externalSecretName }}
                key: {{ .Values.pelican.externalDatabase.auth.usernameKey }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.externalDatabase.auth.externalSecretName }}
                key: {{ .Values.pelican.externalDatabase.auth.passwordKey }}
          {{- end }}
          {{- if .Values.pelican.redis.enabled }}
          - name: REDIS_HOST
            value: {{ .Values.pelican.redis.host | quote }}
          - name: REDIS_PORT
            value: "{{ .Values.pelican.redis.port }}"
          {{- if and .Values.pelican.redis.enabled .Values.pelican.redis.auth.enabled }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.redis.auth.externalSecretName }}
                key: {{ .Values.pelican.redis.auth.passwordKey }}
          {{- end }}
          {{- if .Values.pelican.trustedProxies }}
          - name: TRUSTED_PROXIES
            value: {{ .Values.pelican.trustedProxies | quote }}
          {{- end }}
          - name: CACHE_DRIVER
            value: redis
          - name: CACHE_STORE # while laravel uses CACHE_DRIVER afaik, pelican seems to need this one. I just set both to be sure
            value: redis
          - name: QUEUE_DRIVER
            value: database
          - name: QUEUE_CONNECTION
            value: database
          - name: SESSION_DRIVER
            value: database
          {{- end }}
          {{- if .Values.pelican.appKeyExistingSecret.enabled }}
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.appKeyExistingSecret.name }}
                key: {{ .Values.pelican.appKeyExistingSecret.key }}
          {{- end }}
          # S3 BACKUP
          {{- if .Values.pelican.backup.s3.enabled }}
          - name: AWS_USE_PATH_STYLE_ENDPOINT
            value: {{ .Values.pelican.backup.s3.usePathStyleEndpoint | quote }}
          {{- if .Values.pelican.backup.s3.useAsBackupDriver }}
          - name: APP_BACKUP_DRIVER
            value: s3
          {{- end }}
          - name: AWS_DEFAULT_REGION
          {{- if .Values.pelican.backup.s3.existingSecret.regionKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.backup.s3.existingSecret.name }}
                key: {{ .Values.pelican.backup.s3.existingSecret.regionKey }}
          {{- else }}
            value: {{ .Values.pelican.backup.s3.region | quote }}
          {{- end }}
          - name: AWS_BACKUPS_BUCKET
          {{- if .Values.pelican.backup.s3.existingSecret.bucketKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.backup.s3.existingSecret.name }}
                key: {{ .Values.pelican.backup.s3.existingSecret.bucketKey }}
          {{- else }}
            value: {{ .Values.pelican.backup.s3.bucket | quote }}
          {{- end }}
          - name: AWS_ENDPOINT_URL
          {{- if .Values.pelican.backup.s3.existingSecret.endpointKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.backup.s3.existingSecret.name }}
                key: {{ .Values.pelican.backup.s3.existingSecret.endpointKey }}
          {{- else }}
            value: {{ .Values.pelican.backup.s3.endpoint | quote }}
          {{- end }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.backup.s3.existingSecret.name }}
                key: {{ .Values.pelican.backup.s3.existingSecret.accessKeyIdKey }}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.backup.s3.existingSecret.name }}
                key: {{ .Values.pelican.backup.s3.existingSecret.secretAccessKeyKey }}
          {{- end }}
          # MAILER SETTINGS
          {{- if .Values.pelican.mail.enabled }}
          - name: MAIL_MAILER
            value: {{ .Values.pelican.mail.driver | quote }}
          - name: MAIL_SCHEME
            value: {{ .Values.pelican.mail.scheme | quote }}
          - name: MAIL_HOST
          {{- if .Values.pelican.mail.smtp.existingSecret.hostKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.mail.smtp.existingSecret.name }}
                key: {{ .Values.pelican.mail.smtp.existingSecret.hostKey }}
          {{- else }}
            value: {{ .Values.pelican.mail.smtp.host | quote }}
          {{- end }}
          - name: MAIL_PORT
          {{- if .Values.pelican.mail.smtp.existingSecret.portKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.mail.smtp.existingSecret.name }}
                key: {{ .Values.pelican.mail.smtp.existingSecret.portKey }}
          {{- else }}
            value: {{ .Values.pelican.mail.smtp.port | quote }}
          {{- end }}
          - name: MAIL_FROM_ADDRESS
          {{- if .Values.pelican.mail.smtp.existingSecret.fromAddressKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.mail.smtp.existingSecret.name }}
                key: {{ .Values.pelican.mail.smtp.existingSecret.fromAddressKey }}
          {{- else }}
            value: {{ .Values.pelican.mail.smtp.fromAddress | quote }}
          {{- end }}
          - name: MAIL_FROM_NAME
          {{- if .Values.pelican.mail.smtp.existingSecret.fromNameKey }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.mail.smtp.existingSecret.name }}
                key: {{ .Values.pelican.mail.smtp.existingSecret.fromNameKey }}
          {{- else }}
            value: {{ .Values.pelican.mail.smtp.fromName | quote }}
          {{- end }}
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.mail.smtp.existingSecret.name }}
                key: {{ .Values.pelican.mail.smtp.existingSecret.usernameKey }}
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.pelican.mail.smtp.existingSecret.name }}
                key: {{ .Values.pelican.mail.smtp.existingSecret.passwordKey }}
          {{- end }}

      volumes:
      - name: caddy-config
        configMap:
          name: {{ include "pelican-panel.fullname" . }}-caddy-config
      - name: plugin-downloader-script
        configMap:
          name: {{ include "pelican-panel.fullname" . }}-plugin-downloader-script
      - name: temp
        emptyDir: {}
      - name: framework-cache
        emptyDir: {}
      - name: framework-view-cache
        emptyDir: {}
      - name: framework-sessions
        emptyDir: {}
      - name: filament-cache
        emptyDir: {}
      {{- if .Values.pelican.logsPVC.enabled }}
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "pelican-panel.fullname" . }}-logs
      {{- end }}
      {{- if .Values.pelican.dataPVC.enabled }}
      - name: pelican-data
        persistentVolumeClaim:
          claimName: {{ include "pelican-panel.fullname" . }}-data
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
