{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pelican-panel.fullname" . }}-network-policy
  labels:
    {{- include "pelican-panel.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pelican-panel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: application
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # additional ingress rules from values
    {{- with .Values.networkPolicy.ingressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # allow traffic from test-connection pod
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: test-connection
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- if .Values.networkPolicy.defaultPolicy.traefikIngress.enabled }}
    - to:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.defaultPolicy.traefikIngress.namespaceSelector | nindent 10 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- end }}
  egress:
    # default rules
    {{- if .Values.networkPolicy.defaultPolicy.coreDNSEgress.enabled }}
    - to:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.defaultPolicy.coreDNSEgress.namespaceSelector | nindent 10 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.defaultPolicy.coreDNSEgress.podSelector | nindent 12 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    
    {{- if .Values.networkPolicy.defaultPolicy.allHttpsEgress.enabled }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    {{- end }}

    {{- with .Values.networkPolicy.egressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
